name: Build and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OCaml compiler
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.11
          dune-cache: true

      - name: Install dependencies
        run: |
          opam install . --deps-only

      - name: Show configuration
        run: |
          opam exec -- ocamlc -config
          opam config list
          opam exec -- dune printenv
          opam list

      - name: Build the test suite
        run: opam exec -- dune build

      - name: Run the perf tests
        run: |
          printf '\n\n64\n'
          ITERATIONS=64 opam exec -- dune build @perfs
          printf '\n\n256\n'
          ITERATIONS=256 opam exec -- dune build @perfs
          printf '\n\n512\n'
          ITERATIONS=512 opam exec -- dune build @perfs
          printf '\n\n1024\n'
          ITERATIONS=1024 opam exec -- dune build @perfs
          printf '\n\n2048\n'
          ITERATIONS=2048 opam exec -- dune build @perfs
