name: Build and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OCaml compiler
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.11
          dune-cache: true

      - name: Install dependencies
        run: |
          opam install . --deps-only

      - name: Show configuration
        run: |
          opam exec -- ocamlc -config
          opam config list
          opam exec -- dune printenv
          opam list

      - name: Build the test suite
        run: opam exec -- dune build

      - name: Run the perf tests
        run: |
          printf '1\n'
          ITERATIONS=1 opam exec -- dune build @perfs
          printf '\n\n2\n'
          ITERATIONS=2 opam exec -- dune build @perfs
          printf '\n\n4\n'
          ITERATIONS=4 opam exec -- dune build @perfs
          printf '\n\n8\n'
          ITERATIONS=8 opam exec -- dune build @perfs
          printf '\n\n16\n'
          ITERATIONS=16 opam exec -- dune build @perfs
          printf '\n\n32\n'
          ITERATIONS=32 opam exec -- dune build @perfs
          printf '\n\n48\n'
          ITERATIONS=48 opam exec -- dune build @perfs
